baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
relativeURLs = true

title = "fairydust.space - 🚀"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true

[params]
#  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Lifts you up, higher and higher"
  author = "Cabin Crew"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Change default color scheme with a variant one. Can be "red", "blue", "green", "fairydust".
  themeVariant = "fairydust"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
  title = "fairydust.space - 🚀"
  weight = 1
  landingPageURL = "/en"
  languageName = "English"

[[Languages.en.menu.shortcuts]]
  name = "chat.fairydust.space"
  url = "https://chat.fairydust.space"
  weight = 10

[[Languages.en.menu.shortcuts]]
  name = "Contact us"
  url = "/contact"
  weight = 20

[[Languages.en.menu.shortcuts]]
  name = "Terms of Service"
  url = "https://fairydust.space/_matrix/consent"
  weight = 100

[Languages.de]
  title = "fairydust.space - 🚀"
  weight = 1
  landingPageURL = "/de"
  languageName = "Deutsch"

[[Languages.de.menu.shortcuts]]
  name = "chat.fairydust.space"
  url = "https://chat.fairydust.space"
  weight = 10

[[Languages.de.menu.shortcuts]]
  name = "Kontaktiere uns"
  url = "/contact"
  weight = 20

[[Languages.de.menu.shortcuts]]
  name = "Nutzungsbedingungen (in Englisch)"
  url = "https://fairydust.space/_matrix/consent"
  weight = 100

