baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "fairydust.space - 🚀"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true

[params]
#  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "our awesome launchpad"
  author = "Cabin Crew"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Change default color scheme with a variant one. Can be "red", "blue", "green", "fairydust".
  themeVariant = "fairydust"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
  [Languages.en]
    title = "fairydust.space - 🚀"
    theme = "hugo-theme-learn"
    weight = 1
    languageName = "English"
    contentDir = "content/en"

[[Languages.en.menu.shortcuts]]
  name = "chat.fairydust.space"
  url = "https://chat.fairydust.space"
  weight = 10

[[Languages.en.menu.shortcuts]]
  name = "Contact us"
  url = "contact"
  weight = 20

[Languages.de]
  title = "fairydust.space - 🚀"
  theme = "hugo-theme-learn"
  weight = 1
  languageName = "Deutsch"
  contentDir = "content/de"

[[Languages.de.menu.shortcuts]]
  name = "chat.fairydust.space"
  url = "https://chat.fairydust.space"
  weight = 10

[[Languages.de.menu.shortcuts]]
  name = "Kontaktiere uns"
  url = "contact"
  weight = 20

